export enum PermissionSample1Enum {

  // Issue Permissions
  CREATE_ISSUE = 'CREATE_ISSUE',
  UPDATE_ISSUE = 'UPDATE_ISSUE',
  VIEW_ISSUE = 'VIEW_ISSUE',
  DELETE_ISSUE = 'DELETE_ISSUE',
  UPDATE_ISSUE_STATUS = 'UPDATE_ISSUE_STATUS',
  UPDATE_ISSUE_PRIORITY = 'UPDATE_ISSUE_PRIORITY',
  UPDATE_ISSUE_SEVERITY = 'UPDATE_ISSUE_SEVERITY',

}


export enum PermissionSample2Enum {

  // Issue Permissions

  VIEW_ISSUE = 'VIEW_ISSUE',
  UPDATE_ISSUE_STATUS = 'UPDATE_ISSUE_STATUS',

}
